CotaPedido.WebSite/Controllers/VendasController.cs
using CotaPedido.Entidades;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CotaPedido.WebSite.Models
{
    public class VendasController : Controller
    {
        //
        // GET: /Vendas/
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult ListarCotacoes()
        {
            return View();
        }

      

        public ActionResult ConsultarPedidos()
        {
            var vendedor = RecuperarVendedor();
            if (vendedor == null)
            {
                return RedirectToAction("Vendedor", "Cadastro", null);
            }

            var model = new CotacaoModel();


            model.CarregarPedidos(vendedor.Id);

            return View(model);
        }

        public ActionResult EditarCotacao()
        {
            return View();
        }
        [HttpGet]
        public ActionResult DetalhesPedido(int? id)
        {
            var vendedor = RecuperarVendedor();
            if (vendedor == null)
            {
                return RedirectToAction("Vendedor", "Cadastro", null);
            }

            var model = new CotacaoModel();


            model.CarregarPedido(id.Value);

            return View(model);
        }

        #region Métodos Privados

        private Vendedor RecuperarVendedor()
        {
            return Session["userVendedor"] as Vendedor;
        }
        
        [HttpPost]
        public ActionResult Cotar(int? id, CotacaoModel model)
        {
            var vendedor = RecuperarVendedor();
            if (vendedor == null)
            {
                return RedirectToAction("Vendedor", "Cadastro", null);
            }

            model.CarregarPedido(id.Value);

            model.Itens = CarregaItens(model.Pedido.Itens);

            model.DataLimiteProposta = model.Pedido.Validade.Value.ToString("dd/MM/yyyy");
            model.IdCategoriaPrincipal = model.Pedido.IdCategoriaPrincipal.Value;
            model.Idvendedor = vendedor.Id;    
            model.SituacaoPedido = model.Pedido.SituacaoPedido;
            model.DataCotacao = DateTime.Now.ToString("dd/MM/yyyy");

            return View(model);
        }

        #endregion

        private List<ItemCotacaoModel> CarregaItens(List<ItemPedido> list)
        {
            var itens = new List<ItemCotacaoModel>();

            foreach (var item in list)
            {
                itens.Add(new ItemCotacaoModel
                {
                    NomeProduto = item.Descricao,
                    IdItem = item.Id,
                    IdCategoria = item.IdCategoria,
                    IdSubCategoria = item.IdSubCategoria,
                    IdUnidade = 0, //item.IdUnidade.Value,
                    Quantidade = item.Quantidade.Value,
                    ValorUnitario = 0,
                    ValorTotal = 0,
                });
            }

            return itens;
        }
	}
}

CotaPedido.WebSite/Views/Vendas/ConsultarPedidos.cshtml
@model CotacaoModel
@{
    ViewBag.Title = "Consultar";
}
@{
    var cadastrado = TempData["Success"] != null ? Convert.ToBoolean(TempData["Success"]) : false;
}

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="white-container">
            <span class="title">PESQUISAR PEDIDOS</span>

            <div class="row">
                @using (Html.BeginForm("Consultar", "Vendas", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
                    <div class="col-lg-12 col-sm-12 hero-feature">

                        @if (cadastrado)
                        {
                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-sm-12">
                                    <div class="alert alert-dismissable alert-success">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        <ul><li>Vendedor cadastrado com sucesso!</li></ul>
                                    </div>
                                </div>
                            </div>
                        }

                        @if (!ViewData.ModelState.IsValid)
                        {
                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-sm-12">
                                    <div class="alert alert-dismissable alert-danger">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        @Html.ValidationSummary()
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <table class="table table-bordered tbl-checkout">
                                    <tbody>
                                        <tr>
                                            <td class="content-middle" style="width: 150px;">Categoria Principal</td>
                                            <td colspan="3">
                                                Descrição Categoria Principal
                                            </td>
                                            <td style="width: 120px; text-align: right;">
                                                <div class="btn-group btns-cart">
                                                    <button type="submit" class="btn btn-primary" id="btnIniciar">Pesquisar</button>
                                                </div>
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <table class="table table-bordered tbl-cart">
                                    <thead>
                                        <tr>
                                            <td class="hidden-xs">Data Pedido</td>
                                            <td>Data Limite Propostas</td>
                                            <td>Categoria Principal</td>
                                            <td>Situação</td>
                                            <td></td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @if (Model.Pedidos.Count == 0)
                                        {
                                        <tr><td colspan="5">Sem pedidos para listar.</td></tr>
                                        }
                                        else
                                        {
                                            foreach (var pedido in Model.Pedidos)
                                            {
                                        <tr>
                                            <td class="hidden-xs">
                                                @pedido.DataCadastro.Value.ToString("dd/MM/yyyy")
                                            </td>
                                            <td>
                                                @pedido.Validade.Value.ToString("dd/MM/yyyy")
                                            </td>
                                            <td>
                                                @pedido.Categoria.Nome
                                            </td>
                                            <td>
                                                @pedido.SituacaoPedido.ToString()
                                            </td>
                                            <td style="text-align: center; color:black !important;">
                                                @Html.ActionLink(" ", "DetalhesPedido", "Vendas", new { Id = pedido.Id }, new { @class = "fa fa-search" })
                                            </td>
                                        </tr>
                                            }
                                        }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>
@section ScriptsValidation{
    @Scripts.Render("~/jqueryval")
    @Scripts.Render("~/SolicitarPedido")
}

CotaPedido.WebSite/Views/Vendas/Cotar.cshtml
@model CotacaoModel

@{
    ViewBag.Title = "Cotar";
}


<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="white-container">
            <span class="title">NOVA COTAÇÃO</span>

            <div class="row">
                @using (Html.BeginForm("Cotar", "Vendas", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
                        @Html.HiddenFor(x => x.Id)
                        @Html.HiddenFor(x => x.DataLimiteProposta)
                        @Html.HiddenFor(x => x.DataCotacao)
                        @Html.HiddenFor(x => x.Idvendedor)
                        @Html.HiddenFor(x => x.IdCategoriaPrincipal)

                    <div class="col-lg-12 col-sm-12 hero-feature">
                        @if (!ViewData.ModelState.IsValid)
                        {
                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-sm-12">
                                    <div class="alert alert-dismissable alert-danger">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        @Html.ValidationSummary()
                                    </div>
                                </div>
                            </div>
                        }

                        <table class="table table-bordered tbl-checkout">
                            <tbody>
                                <tr>
                                    <td style="width: 180px;">Categoria Principal</td>
                                    <td>
                                        @Model.Pedido.Categoria.Nome
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                        <br />
                        <br />

                        <table id="produtos" class="table table-bordered tbl-cart">
                            <thead>
                                <tr>
                                    <td>Produto</td>
                                    <td>Categoria</td>
                                    <td>Subcategoria</td>
                                    <td>Un. Medida</td>
                                    <td class="td-qty">Quantidade</td>
                                    <td>Valor Unitário</td>
                                    <td>Total</td>
                                </tr>
                            </thead>
                            <tbody>
                                @if (Model.Pedido.Itens.Count == 0)
                                {
                                    <tr><td colspan="5">Sem itens para listar.</td></tr>
                                }
                                else
                                {
                                    for (var i = 0; i < Model.Pedido.Itens.Count; i++)
                                    {
                                        <tr>
                                            <td class="hidden-xs">
                                                @Html.DisplayFor(x => x.Pedido.Itens[i].Descricao)
                                                @Html.HiddenFor(x => x.Itens[i].NomeProduto)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x => x.Pedido.Itens[i].IdCategoria)
                                                @Html.HiddenFor(x => x.Itens[i].IdCategoria)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x => x.Pedido.Itens[i].SubCategoria)
                                                @Html.HiddenFor(x => x.Itens[i].SubCategoria)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x => x.Pedido.Itens[i].IdUnidade)
                                                @Html.HiddenFor(x => x.Itens[i].IdUnidade)
                                            </td>
                                            <td>
                                                @Html.DisplayFor(x => x.Pedido.Itens[i].Quantidade)
                                                @Html.HiddenFor(x => x.Itens[i].Quantidade)
                                            </td>
                                            <td>
                                                @Html.TextBoxFor(x => x.Itens[i].ValorUnitario, new { @class = "form-control text-right" })
                                            </td>
                                            <td>
                                                @Html.TextBoxFor(x => x.Itens[i].ValorTotal, new { @class = "form-control text-right" })
                                            </td>
                                        </tr>
                                    }
                                }
                        </table>

                        <br />
                        <br />

                        <div class="btn-group btns-cart">
                            <button type="submit" class="btn btn-primary">Finalizar</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="modelAlert" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Alerta!</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

CotaPedido.WebSite/Views/Vendas/DetalhesPedido.cshtml
@model CotacaoModel

@{
    ViewBag.Title = "DetalhesPedido";
}

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="white-container">
            <span class="title">DETALHES DO PEDIDO</span>
            <div class="row">
                <div class="col-lg-12 col-sm-12 hero-feature">
                    @if (!ViewData.ModelState.IsValid)
                    {
                        <div class="row">
                            <div class="col-md-12 col-lg-12 col-sm-12">
                                <div class="alert alert-dismissable alert-danger">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    @Html.ValidationSummary()
                                </div>
                            </div>
                        </div>
                    }

                    @using (Html.BeginForm("Cotar", "Vendas", new { id = Model.Pedido.Id }, FormMethod.Post ))
                    {
                        <div class="btn-group btns-cart">
                            <button type="submit" class="btn btn-primary" id="btnIncluir">Iniciar Cotação</button>
                        </div>
                    }
                    <br /><br />

                    <table class="table table-bordered tbl-checkout">
                        <tbody>
                            <tr>
                                <td style="width: 180px;">Categoria Principal</td>
                                <td>
                                    @Model.Pedido.Categoria.Nome
                                </td>
                            </tr>
                        </tbody>
                    </table>

                    <table id="produtos" class="table table-bordered tbl-cart">
                        <thead>
                            <tr>
                                <td>Produto</td>
                                <td>Categoria</td>
                                <td>Subcategoria</td>
                                <td class="td-qty">Quantidade</td>
                                <td>Un. Medida</td>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Pedido.Itens.Count == 0)
                            {
                                <tr><td colspan="5">Sem itens para listar.</td></tr>
                            }
                            else
                            {
                                foreach (var item in Model.Pedido.Itens)
                                {
                                    <tr>
                                        <td class="hidden-xs">
                                            @item.Descricao
                                        </td>
                                        <td>
                                            @item.IdCategoria
                                        </td>
                                        <td>
                                            @item.SubCategoria
                                        </td>
                                        <td>
                                            @item.Quantidade
                                        </td>
                                        <td>
                                            @item.IdUnidade
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div id="modelAlert" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Alerta!</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>

@section ScriptsValidation{
    @Scripts.Render("~/NovaCompra")
}

CotaPedido.WebSite/Views/Vendas/EditarCotacao.cshtml
@{
    ViewBag.Title = "EditarCotacao";
}

<h2>EditarCotacao</h2>

CotaPedido.WebSite/Views/Vendas/Index.cshtml
@{
    ViewBag.Title = "Vendas";
}

<h2>Index</h2>

CotaPedido.WebSite/Views/Vendas/ListarCotacoes.cshtml
@model PedidoModel

@{
    ViewBag.Title = "Listar Cotações";
}

<div class="container main-container">
    <div class="row">
        <!-- Cart -->
        <div class="col-lg-12 col-md-12 col-sm-12">
            <div class="col-lg-12 col-sm-12">
                <span class="title">MINHAS COTAÇÕES</span>
            </div>
            <div class="col-lg-12 col-sm-12 hero-feature">

                @if (TempData["CotacaoEditada"] != null)
                {
                    <div class="row">
                        <div class="col-md-12 col-lg-12 col-sm-12">
                            <div class="alert alert-dismissable alert-success">
                                <button type="button" class="close" data-dismiss="alert">×</button>
                                Sua cotação foi editada com sucesso!
                            </div>
                        </div>
                    </div>
                }
                <table class="table table-bordered tbl-cart">
                    <thead>
                        <tr>
                            <td class="hidden-xs">Data Cotação</td>
                            <td>Data Limite Proposta</td>
                            <td>Categoria Principal</td>
                            <td>Situação</td>
                            <td></td>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="hidden-xs">
                                11/01/2015
                            </td>
                            <td>
                                11/01/2015
                            </td>
                            <td>
                                Descrição Categoria
                            </td>
                            <td>
                                Pendente
                            </td>
                            <td style="text-align: center; color:black !important;">
                                Editar Cotação | Excluir Cotação | Visualizar Cotação
                            </td>
                        </tr>

                        <tr>
                            <td class="hidden-xs">
                                11/01/2015
                            </td>
                            <td>
                                11/01/2015
                            </td>
                            <td>
                                Descrição Categoria
                            </td>
                            <td>
                                Pendente
                            </td>
                            <td style="text-align: center; color:black !important;">
                                Editar Cotação | Excluir Cotação | Visualizar Cotação
                            </td>
                        </tr>

                        <tr>
                            <td class="hidden-xs">
                                11/01/2015
                            </td>
                            <td>
                                11/01/2015
                            </td>
                            <td>
                                Descrição Categoria
                            </td>
                            <td>
                                Pendente
                            </td>
                            <td style="text-align: center; color:black !important;">
                                Editar Cotação | Excluir Cotação | Visualizar Cotação
                            </td>
                        </tr>

                        <tr>
                            <td class="hidden-xs">
                                11/01/2015
                            </td>
                            <td>
                                11/01/2015
                            </td>
                            <td>
                                Descrição Categoria
                            </td>
                            <td>
                                Pendente
                            </td>
                            <td style="text-align: center; color:black !important;">
                                Editar Cotação | Excluir Cotação | Visualizar Cotação
                            </td>
                        </tr>

                        <tr>
                            <td class="hidden-xs">
                                11/01/2015
                            </td>
                            <td>
                                11/01/2015
                            </td>
                            <td>
                                Descrição Categoria
                            </td>
                            <td>
                                Pendente
                            </td>
                            <td style="text-align: center; color:black !important;">
                                Editar Cotação | Excluir Cotação | Visualizar Cotação
                            </td>
                        </tr>

                        <tr>
                            <td class="hidden-xs">
                                11/01/2015
                            </td>
                            <td>
                                11/01/2015
                            </td>
                            <td>
                                Descrição Categoria
                            </td>
                            <td>
                                Pendente
                            </td>
                            <td style="text-align: center; color:black !important;">
                                Editar Cotação | Excluir Cotação | Visualizar Cotação
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
        <!-- End Cart -->
    </div>
</div>

@section ScriptsValidation{
    @Scripts.Render("~/ListarCompras")
}