CotaPedido.WebSite/Controllers/ComprasController.cs
using CotaPedido.Entidades;
using CotaPedido.Entidades.Enum;
using CotaPedido.Infra.Repositorios;
using System;
using System.Linq;
using System.Transactions;
using System.Web.Mvc;

namespace CotaPedido.WebSite.Models
{
    public class ComprasController : Controller
    {
        #region Métodos Públicos

        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Solicitar()
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }
            var model = new PedidoModel { IdComprador = comprador.Id, DataPedido = DateTime.Now.ToString("dd/MM/yyyy") };


            return View(model);
        }

        [HttpPost]
        public ActionResult Solicitar(PedidoModel model)
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }

            DateTime data;
            if (DateTime.TryParse(model.DataLimiteProposta, out data))
            {
                if (data < DateTime.Now)
                {
                    ModelState.AddModelError("DataLimiteProposta", "A Data Limite Proposta não pode ser inferior a data atual");
                }
            }

            if (ModelState.IsValid)
            {
                var pedido = new Pedido
                {
                    DataCadastro = Convert.ToDateTime(model.DataPedido),
                    Validade = Convert.ToDateTime(model.DataLimiteProposta),
                    SituacaoPedido = SituacaoPedido.EmAberto,
                    IdComprador = model.IdComprador,
                    IdCategoriaPrincipal = model.IdCategoriaPrincipal,
                    Status = true
                };

                var pedidoRepositorio = new RepositorioPedido();
                pedidoRepositorio.Insert(pedido);
                model.Id = pedido.Id;

                TempData.Add("Pedido", model);
                return RedirectToAction("Nova");
            }

            return View(model);
        }

        public ActionResult Nova()
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }

            var model = TempData["Pedido"] as PedidoModel;
            if (model == null)
            {
                return RedirectToAction("Solicitar");
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Nova(PedidoModel model)
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }

            if (model.Itens.Count == 0)
            {
                ModelState.AddModelError("", "Inclua pelo menos um item em seu pedido");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var itensPedido = model.Itens.Select(x => new ItemPedido
                    {
                        IdPedido = model.Id,
                        Quantidade = x.Quantidade,
                        Descricao = x.NomeProduto,
                        IdCategoria = x.IdCategoria,
                        IdSubCategoria = x.IdSubcategoria,
                        IdUnidade = x.IdUnidade
                    }).ToList();

                    using (var scope = new TransactionScope())
                    {
                        var pedidoRepositorio = new RepositorioPedido();
                        var pedido = pedidoRepositorio.Get(model.Id);
                        pedido.SituacaoPedido = SituacaoPedido.Pendente;
                        pedidoRepositorio.Update(pedido);

                        var itemPedidoRepositorio = new RepositorioItemPedido();

                        foreach (var item in itensPedido)
                        {
                            itemPedidoRepositorio.Insert(item);
                        }

                        scope.Complete();
                    }
                    TempData.Add("PedidoCadastrado", true);
                    return RedirectToAction("Solicitar");
                }
                catch
                {
                    ModelState.AddModelError("", "Ocorreu um erro ao tentar gravar pedido");
                }
            }
            return View(model);
        }

        public ActionResult Editar()
        {
            return View();
        }

        public ActionResult Listar()
        {
            return View();
        }

        public ActionResult ListarPedidos()
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }

            if (TempData["PedidoEditado"] != null)
            {
                ViewBag.EditSuccess = true;
            }

            var model = new PedidoModel();
            model.CarregarPedidos(comprador.Id);

            return View(model);
        }

        public ActionResult EditarPedido(int Id)
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }

            var model = new PedidoModel();
            model.CarregarItens(Id);
            model.CarregarPedido(Id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditarPedido(PedidoModel model)
        {
            var comprador = RecuperarComprador();
            if (comprador == null)
            {
                return RedirectToAction("Comprador", "Cadastro", null);
            }

            if (model.Itens.Count == 0)
            {
                ModelState.AddModelError("", "Inclua pelo menos um item em seu pedido");
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var itensPedido = model.Itens.Select(x => new ItemPedido
                    {
                        Id = x.Id,
                        IdPedido = model.Id,
                        Quantidade = x.Quantidade,
                        Descricao = x.NomeProduto,
                        IdCategoria = x.IdCategoria,
                        IdSubCategoria = x.IdSubcategoria
                    }).ToList();

                    var itemPedidoRepositorio = new RepositorioItemPedido();

                    var itensPedidoEditar = itensPedido.Where(x => x.Id != 0).ToList();
                    var itensPedidoInserir = itensPedido.Where(x => x.Id == 0).ToList();

                    using (var scope = new TransactionScope())
                    {
                        var pedidoRepositorio = new RepositorioPedido();
                        var pedido = pedidoRepositorio.Get(model.Id);
                        pedido.SituacaoPedido = SituacaoPedido.Pendente;
                        pedidoRepositorio.Update(pedido);

                        foreach (var item in itensPedidoInserir)
                        {
                            itemPedidoRepositorio.Insert(item);
                        }

                        foreach (var item in itensPedidoEditar)
                        {
                            itemPedidoRepositorio.Update(item);
                        }
                        
                        scope.Complete();
                    }

                    TempData.Add("PedidoEditado", true);
                    return RedirectToAction("ListarPedidos");
                }
                catch
                {
                    ModelState.AddModelError("", "Ocorreu um erro ao tentar editar pedido");
                }
            }

            return View(model);
        }

        public ActionResult Comparar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult GetSubCategorias(int idCategoria)
        {
            if (idCategoria <= 0)
            {
                throw new ArgumentException("O parâmetro idCategoria é obrigatório");
            }

            var subCategoriaRepositorio = new RepositorioSubGrupo();
            var subCategorias = subCategoriaRepositorio.GetAll().Where(x => x.IdGrupo == idCategoria);

            return Json(subCategorias);
        }

        [HttpPost]
        public ActionResult AdicionarSubcategoria(string nome, int idCategoria)
        {
            var message = "";
            var select = "";
            var success = false;
            if (string.IsNullOrEmpty(nome))
            {
                message = "O campo Nome é obrigatório.";
            }
            else
            {
                var repositorioSubcategoria = new RepositorioSubGrupo();
                var repositorioCategoria = new RepositorioGrupo();
                try
                {
                    var subGrupo = new SubGrupo { IdGrupo = idCategoria, Nome = nome };
                    var subGrupos = repositorioSubcategoria.GetAll().Where(x => x.Nome.ToUpper() == subGrupo.Nome.ToUpper()).ToList();
                    if (subGrupos.Count() > 0)
                    {
                        message = "Já existe uma subcategoria com esse nome";
                    }
                    else
                    {
                        success = true;
                        repositorioSubcategoria.Insert(subGrupo);
                        subGrupos = repositorioSubcategoria.GetAll().Where(x => x.IdGrupo == idCategoria).ToList();
                        subGrupos.ForEach(x =>
                        {

CotaPedido.WebSite/Views/Compras/EditarPedido.cshtml
@model PedidoModel
@{
    ViewBag.Title = "Editar Pedido";
}

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="white-container">
            <span class="title">EDITAR PEDIDO</span>

            <div class="row">
                @using (Html.BeginForm(Model.SituacaoPedido == SituacaoPedido.Pendente ? "" : "EditarPedido", "Compras", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
                    @Html.HiddenFor(x => x.Id)
                    @Html.HiddenFor(x => x.DataLimiteProposta)
                    @Html.HiddenFor(x => x.DataPedido)
                    @Html.HiddenFor(x => x.IdComprador)
                    @Html.HiddenFor(x => x.IdCategoriaPrincipal)
                    <div class="col-lg-12 col-sm-12 hero-feature">
                        @if (!ViewData.ModelState.IsValid)
                        {
                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-sm-12">
                                    <div class="alert alert-dismissable alert-danger">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        @Html.ValidationSummary()
                                    </div>
                                </div>
                            </div>
                        }
                        <table class="table table-bordered tbl-checkout">
                            <tbody>
                                <tr>
                                    <td>Categoria</td>
                                    <td>
                                        @Html.DropDownList("categoria", Model.GetSelectCategorias(), "Selecione a categoria", new { id = "categoria", @class = "form-control" })
                                    </td>
                                    <td>Subcategoria</td>
                                    <td>
                                        <select class="form-control" id="subcategoria">
                                            <option value="">Selecione a subcategoria</option>
                                        </select>
                                    </td>
                                    <td style="text-align:center;">
                                        <a href="#" id="btnNovaCategoria" class="btn btn-primary" style="color:#FFFFFF;display:inline-block;">Adicionar Subcategoria</a>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Produto</td>
                                    <td>
                                        <input id="produto" type="text" name="" class="form-control" />
                                    </td>
                                    <td>Quantidade</td>
                                    <td colspan="2">
                                        <input id="quantidade" type="text" name="" class="form-control" />
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                        <div class="btn-group btns-cart">
                            <button type="button" class="btn btn-primary" id="btnIncluir">Incluir</button>
                        </div>
                        <br /><br />
                        <table id="produtos" class="table table-bordered tbl-cart">
                            <thead>
                                <tr>
                                    <td>Produto</td>
                                    <td>Categoria</td>
                                    <td>Subcategoria</td>
                                    <td class="td-qty">Quantidade</td>
                                    <td>Remover</td>
                                </tr>
                            </thead>
                            <tbody>
                                @for (var i = 0; i < Model.Itens.Count; i++)
                                {
                                    <tr>
                                        <td>
                                            <input type="hidden" value="@i" class="index" disabled />
                                            @Html.HiddenFor(x => x.Itens[i].NomeProduto)
                                            @Model.Itens[i].NomeProduto
                                            @Html.HiddenFor(x => x.Itens[i].Id)
                                        </td>
                                        <td>
                                            @Html.HiddenFor(x => x.Itens[i].IdCategoria)
                                            @Model.Itens[i].Categoria.Nome
                                        </td>
                                        <td>
                                            @Html.HiddenFor(x => x.Itens[i].IdSubcategoria)
                                            @Model.Itens[i].SubCategoria.Nome
                                        </td>
                                        <td>
                                            @Html.TextBoxFor(x => x.Itens[i].Quantidade, new { @class = "input-qty form-control text-center" })
                                        </td>
                                        <td class="text-center content-middle">
                                            <a href="#" class="remove_cart" rel="2">
                                                <i class="fa fa-trash-o fa-2x"></i>
                                            </a>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                        @if (Model.SituacaoPedido == SituacaoPedido.EmAberto)
                        {
                            <div class="btn-group btns-cart">
                                <button type="submit" class="btn btn-primary">Continuar</button>
                            </div>
                        }
                    </div>
                }
            </div>
            <!-- End Cart -->
        </div>
    </div>
</div>

<!-- Modal -->
<div id="modelAlert" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Alerta!</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_NovaSubcategoria")

@section ScriptsValidation{
    @Scripts.Render("~/NovaCompra")
}

CotaPedido.WebSite/Views/Compras/Index.cshtml
@{
    ViewBag.Title = "Compras";
}

<h2>Index</h2>

CotaPedido.WebSite/Views/Compras/ListarPedidos.cshtml
@model PedidoModel
@{
    ViewBag.Title = "Listar Pedidos";
}

@{
    var cadastrado = TempData["Success"] != null ? Convert.ToBoolean(TempData["Success"]) : false;
}

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="white-container">
            <span class="title">MEUS PEDIDOS</span>

            <div class="row">

                <div class="col-lg-12 col-sm-12 hero-feature">

                    @if (cadastrado)
                    {
                        <div class="row">
                            <div class="col-md-12 col-lg-12 col-sm-12">
                                <div class="alert alert-dismissable alert-success">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    <ul><li>Comprador cadastrado com sucesso!</li></ul>
                                </div>
                            </div>
                        </div>
                    }

                    @if (TempData["PedidoEditado"] != null)
                    {
                        <div class="row">
                            <div class="col-md-12 col-lg-12 col-sm-12">
                                <div class="alert alert-dismissable alert-success">
                                    <button type="button" class="close" data-dismiss="alert">×</button>
                                    Seu pedido foi editado com sucesso!
                                </div>
                            </div>
                        </div>
                    }
                    
                    <table class="table table-bordered tbl-cart">
                        <thead>
                            <tr>
                                <td class="hidden-xs">Data Pedido</td>
                                <td>Data Limite Propostas</td>
                                <td>Categoria Principal</td>
                                <td>Situação</td>
                                <td></td>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model.Pedidos.Count == 0)
                            {
                                <tr><td colspan="5">Sem pedidos para listar.</td></tr>
                            }
                            else
                            {
                                foreach (var pedido in Model.Pedidos)
                                {
                                    <tr>
                                        <td class="hidden-xs">
                                            @pedido.DataCadastro.Value.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>
                                            @pedido.Validade.Value.ToString("dd/MM/yyyy")
                                        </td>
                                        <td>
                                            @pedido.Categoria.Nome
                                        </td>
                                        <td>
                                            @pedido.SituacaoPedido.ToString()
                                        </td>
                                        <td style="text-align: center; color:black !important;">
                                            @Html.ActionLink(" ", "EditarPedido", "Compras", new { Id = pedido.Id }, new { @class = "fa fa-search" })
                                        </td>
                                    </tr>
                                }
                            }
                        </tbody>
                    </table>
                </div>

            </div>
        </div>
    </div>
</div>

@section ScriptsValidation{
    @Scripts.Render("~/ListarCompras")
}

CotaPedido.WebSite/Views/Compras/Nova.cshtml
@model PedidoModel
@{
    ViewBag.Title = "Nova Compra";
}

<div class="container">
    <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="white-container">
            <span class="title">NOVA COMPRA</span>

            <div class="row">
                @using (Html.BeginForm("Nova", "Compras", FormMethod.Post))
                {
                    @Html.AntiForgeryToken();
                    @Html.HiddenFor(x => x.Id)
                    @Html.HiddenFor(x => x.DataLimiteProposta)
                    @Html.HiddenFor(x => x.DataPedido)
                    @Html.HiddenFor(x => x.IdComprador)
                    @Html.HiddenFor(x => x.IdCategoriaPrincipal)
                    <div class="col-lg-12 col-sm-12 hero-feature">
                        @if (!ViewData.ModelState.IsValid)
                        {
                            <div class="row">
                                <div class="col-md-12 col-lg-12 col-sm-12">
                                    <div class="alert alert-dismissable alert-danger">
                                        <button type="button" class="close" data-dismiss="alert">×</button>
                                        @Html.ValidationSummary()
                                    </div>
                                </div>
                            </div>
                        }
                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <table class="table table-bordered tbl-checkout">
                                    <tbody>
                                        <tr>
                                            <td>Categoria</td>
                                            <td>
                                                @Html.DropDownList("categoria", Model.GetSelectCategorias(), "Selecione a categoria", new { id = "categoria", @class = "form-control" })
                                            </td>
                                            <td>Subcategoria</td>
                                            <td>
                                                <select class="form-control" id="subcategoria">
                                                    <option value="">Selecione a subcategoria</option>
                                                </select>
                                            </td>
                                            <td style="text-align:center;">
                                                <a href="#" id="btnNovaCategoria" class="btn btn-primary" style="color:#FFFFFF;display:inline-block;">Adicionar Subcategoria</a>
                                            </td>
                                        </tr>
                                        <tr>
                                            <td>Produto</td>
                                            <td>
                                                <input id="produto" type="text" name="" class="form-control" />
                                            </td>
                                            <td>Quantidade</td>
                                            <td colspan="2">
                                                <input id="quantidade" type="text" name="" class="form-control" />
                                            </td>
                                        </tr>
                                    </tbody>
                                </table>
                                <div class="btn-group btns-cart">
                                    <button type="button" class="btn btn-primary" id="btnIncluir">Incluir</button>
                                </div>
                                <br /><br />
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-lg-12 col-md-12 col-sm-12">
                                <table id="produtos" class="table table-bordered tbl-cart">
                                    <thead>
                                        <tr>
                                            <td>Produto</td>
                                            <td>Categoria</td>
                                            <td>Subcategoria</td>
                                            <td class="td-qty">Quantidade</td>
                                            <td>Remover</td>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        @for (var i = 0; i < Model.Itens.Count; i++)
                                        {
                                            <tr>
                                                <td>
                                                    <input type="hidden" value="@i" class="index" disabled />
                                                    @Html.HiddenFor(x => x.Itens[i].NomeProduto)
                                                    @Model.Itens[i].NomeProduto
                                                </td>
                                                <td>
                                                    @Html.HiddenFor(x => x.Itens[i].IdCategoria)
                                                    @Model.Itens[i].Categoria.Nome
                                                </td>
                                                <td>
                                                    @Html.HiddenFor(x => x.Itens[i].IdSubcategoria)
                                                    @Model.Itens[i].SubCategoria.Nome
                                                </td>
                                                <td>
                                                    @Html.TextBoxFor(x => x.Itens[i].Quantidade, new { @class = "input-qty form-control text-center" })
                                                </td>
                                                <td class="text-center content-middle">
                                                    <a href="#" class="remove_cart" rel="2">
                                                        <i class="fa fa-trash-o fa-2x"></i>
                                                    </a>
                                                </td>
                                            </tr>
                                        }
                                    </tbody>
                                </table>
                                <div class="btn-group btns-cart">
                                    <button type="submit" class="btn btn-primary">Continuar</button>
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div id="modelAlert" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Alerta!</h4>
            </div>
            <div class="modal-body">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
            </div>
        </div>
    </div>
</div>
@Html.Partial("_NovaSubcategoria")

@section ScriptsValidation{
    @Scripts.Render("~/NovaCompra")
}

CotaPedido.WebSite/Views/Compras/_NovaSubcategoria.cshtml
<div id="newSubcategory" class="modal fade" role="dialog">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Cadastrar Subcategoria</h4>
            </div>
            <div class="modal-body">
                <table class="table table-bordered tbl-checkout">
                    <tbody>
                        <tr>
                            <td style="vertical-align: middle;">Nome</td>
                            <td>
                                <input id="novaSubcategoria" type="text" name="" class="form-control" />
                                <div class="text-danger" id="errorNovaSubcategoria"></div>
                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
                <button type="button" class="btn btn-primary" id="btnIncluirNovaSubcategoria">Gravar</button>
            </div>
        </div>
    </div>
</div>